# Generated by Django 4.1.3 on 2023-05-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherreport',
            name='location',
            field=models.CharField(default='abc', max_length=250),
            preserve_default=False,
        ),
    ]
